### ISSUE TITLE
Missing README.md file

### ISSUE THREAD

**Issue by obiwac** [NovAti0n/Portfolio#2] opened 2022-02-25 15:30 UTC
@NovAti0n how am i supposed t o know hwat to read?

**Comment by drakeerv** [comment] 2022-03-07 13:55
I also need this fixed STAT, ASAP, PRONTO, NOW

**Comment by NoaQuenon** [comment] 2022-03-09 07:29
The problem is now fixed, thanks a lot for this issue @obiwac

**Closed as completed by NoaQuenon** 2022-03-09 07:29 UTC
Labels: documentation

**Comment by NoaQuenon** [comment] 2022-03-09 07:31
> I also need this fixed STAT, ASAP, PRONTO, NOW

And I need you to calm down or I will be forced to ban you FOREVER :angry: 

Be careful @drakeerv, I'm watching you.

**Comment by obiwac** [comment] 2022-03-09 13:13
Watch out @drakeerv , I think he's watching you 😳
