### ISSUE TITLE
Random Broken

### ISSUE THREAD

**Issue by drakeerv** [NovAti0n/Portfolio#1] opened 2022-02-24 16:39 UTC
RANDOM THINGY BROKEN D:<

**Comment by NoaQuenon** [comment] 2022-02-24 16:48
Hey @drakeerv ! Thank you for opening this issue. Could you provide more information (maybe some screenshots or explanations)? I can't reproduce your issue on my side.

Looking forward to your reply!

**Comment by drakeerv** [comment] 2022-02-24 17:28
WHEN I CLICK THE LINK IT GOES TO NEVER GONNA GIVE YOU UP (https://www.youtube.com/watch?v=dQw4w9WgXcQ). 
![Screenshot](https://i.ibb.co/dK00BDp/Screenshot-2022-02-24-12-24-03-PM.png)

**Comment by drakeerv** [comment] 2022-02-24 17:28
*EVERY TIME

**Comment by NoaQuenon** [comment] 2022-02-25 09:40
Thank you for reporting this major bug. Unfortunately, all our engineers are busy implementing new features and this issue won't be fixed before Q4 2024.

Thank you for your patience and understanding.

**Closed as completed** 2022-02-25 09:40 UTC
Labels: wontfix

**Comment by drakeerv** [comment] 2022-02-25 14:25
I EXPECT IT TO BE FIXED

**Comment by obiwac** [comment] 2022-02-25 15:29
@NovAti0n our team also relies on this bugfix, if you don't fix it, we'll regrettably have to remove Belgium from NATO :(

**Comment by drakeerv** [comment] 2022-03-07 13:56
@NovAti0nTHIS NEEDS TO BE FIXED ASAP

**Comment by obiwac** [comment] 2022-03-07 21:34
> @NovAti0n our team also relies on this bugfix, if you don't fix it, we'll regrettably have to remove Belgium from NATO :(

lmfao I had forgotten about this but this aged like cheese which doesn't age particularly well

**Comment by NoaQuenon** [comment] 2022-03-07 22:01
cheese never ages. checkmate vegans

**Comment by drakeerv** [comment] 2022-03-07 23:09
Aged cheddar

**Comment by NoaQuenon** [comment] 2022-03-09 07:25
:cry:
